quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres.rktnsbnppeplcwyfhcib
quarkus.datasource.password=Kilangminyak00
quarkus.datasource.jdbc.url=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres

quarkus.hibernate-orm.database.generation=update


# Konfigurasi SmallRye JWT
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem
quarkus.native.resources.includes=publicKey.pem

quarkus.smallrye-openapi.path=/pembukuan/openapi
quarkus.swagger-ui.path=/pembukuan/swagger-ui
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.filter=true
quarkus.swagger-ui.enable=true

mp.openapi.extensions.enabled=true
mp.openapi.scan.disable=false

# Metadata API
mp.openapi.servers[0].url=http://localhost:8080
mp.openapi.info.title=Aplikasi Pembukuan API
mp.openapi.info.version=1.0.1
mp.openapi.info.description=API untuk mencatat pemasukan dan pengeluaran.
mp.openapi.info.contact.name=Akbar Rizky
mp.openapi.info.contact.email=akbar@example.com