quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/pembukuan

quarkus.hibernate-orm.database.generation=update
quarkus.smallrye-jwt.sign-key-location=privateKey.pem
quarkus.smallrye-jwt.verify-publickey-location=publicKey.pem
quarkus.smallrye-jwt.issuer=app

quarkus.smallrye-openapi.path=/pembukuan/swagger
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/pembukuan/swagger-ui
quarkus.swagger-ui.filter=true
quarkus.swagger-ui.enable=true

mp.openapi.extensions.enabled=true
mp.openapi.scan.disable=false

# Metadata API
mp.openapi.servers[0].url=http://localhost:8080
mp.openapi.info.title=Aplikasi Pembukuan API
mp.openapi.info.version=1.0.0
mp.openapi.info.description=API untuk mencatat pemasukan dan pengeluaran.
mp.openapi.info.contact.name=Akbar Rizky
mp.openapi.info.contact.email=akbar@example.com